openapi: 3.0.0
info:
  title: ToyCycle API
  version: 1.0.0
paths:
  /api/toys:
    get:
      summary: Get list of toys
      responses:
        '200':
          description: A list of toys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Toy'
    post:
      summary: Add a new toy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Toy'
      responses:
        '201':
          description: Toy created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Toy'
components:
  schemas:
    Toy:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [available, exchanged]
        images:
          type: array
          items:
            type: string
        tokenValue:
          type: integer
      required:
        - name
        - description
        - tokenValue
